In [1]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.style as style
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import imblearn
import sys
from sklearn.model_selection import train_test_split

In [2]:
#ls

In [3]:
df = pd.read_csv("intrusion_data.csv")
#null_columns=df.columns[df.isnull().any()]
#df[null_columns].isnull().sum()
df.isnull().sum()

X                               0
duration                        9
land                            0
wrong_fragment                  0
urgent                         14
hot                            12
num_failed_logins              12
logged_in                      18
num_compromised                11
root_shell                     11
su_attempted                   10
num_root                       17
num_file_creations             12
num_shells                      6
num_access_files                8
num_outbound_cmds               0
is_host_login                   0
is_guest_login                 12
rerror_rate                     7
srv_rerror_rate                11
diff_srv_rate                  10
srv_diff_host_rate             11
dst_host_count                 11
dst_host_srv_diff_host_rate    11
dst_host_rerror_rate           10
dst_host_srv_rerror_rate        9
serror_rate                    17
Target                          8
dtype: int64

In [4]:
df.dtypes

X                                int64
duration                       float64
land                             int64
wrong_fragment                   int64
urgent                         float64
hot                            float64
num_failed_logins              float64
logged_in                      float64
num_compromised                float64
root_shell                     float64
su_attempted                   float64
num_root                       float64
num_file_creations             float64
num_shells                     float64
num_access_files               float64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                 float64
rerror_rate                    float64
srv_rerror_rate                float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                 float64
dst_host_srv_diff_host_rate    float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate 

In [5]:
df.Target.value_counts()
df.Target.dtype
#df.Target.head()
print("Mode is: ",(df.Target.mode()))

Mode is:  0    0.0
dtype: float64


In [6]:
df.Target = df.Target.astype(np.object)
df.Target = df.Target.fillna(df.Target.mode())
#df.Target = df.Target.replace(to_replace = 'NA',value = df.Target.mode())
print("Mode is: ", int(df.Target.mode()[0]))
#print("Type of:", type(df.Target.mode()))
print(df.Target.head())
print("Null values: ", df.Target.isnull().sum())
print("--------------------------------")
df.Target = df.Target.fillna(int(df.Target.mode()[0]))
print(df.Target.head())
print("Null values: ", df.Target.isnull().sum())
print("Unique: ", df.Target.unique())
print("dtype: ", df.Target.dtype)

Mode is:  0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Target, dtype: float64
Null values:  8
--------------------------------
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Target, dtype: float64
Null values:  0
Unique:  [0. 1.]
dtype:  float64


In [7]:
df["Target"]= df["Target"].astype(np.int64)
print(df.Target.head())
print("Null values: ", df.Target.isnull().sum())
print("Unique: ", df.Target.unique())
print("dtype: ", df.Target.dtype)

0    0
1    0
2    0
3    0
4    0
Name: Target, dtype: int64
Null values:  0
Unique:  [0 1]
dtype:  int64


In [8]:
df['duration'].mean()
df.duration = df.fillna(value=df['duration'].mean())
df.urgent = df.fillna(value=df.urgent.mean())
df.urgent.isnull().sum()

df['land'].mode()
df.land = df.fillna(value=df['land'].mode())
df.land.isnull().sum()

df['wrong_fragment'].mode()
df.land = df.fillna(value=df['wrong_fragment'].mode())
df.land.isnull().sum()

df['num_outbound_cmds'].mode()
df.land = df.fillna(value=df['num_outbound_cmds'].mode())
df.land.isnull().sum()

df['X'].mode()
df.land = df.fillna(value=df['X'].mode())
df.land.isnull().sum()

df['is_host_login'].mode()
df.land = df.fillna(value=df['is_host_login'].mode())
df.land.isnull().sum()

df['hot'].mean()
df.hot = df.fillna(value=df['hot'].mean())
df.hot.isnull().sum()

df['num_failed_logins'].mean()
df.num_failed_logins = df.fillna(value=df['num_failed_logins'].mean())
df.num_failed_logins.isnull().sum()

df['logged_in'].mean()
df.logged_in = df.fillna(value=df['logged_in'].mean())
df.logged_in.isnull().sum()

df['num_compromised'].mean()
df.num_compromised = df.fillna(value=df['num_compromised'].mean())
df.num_compromised.isnull().sum()

df['root_shell'].mean()
df.root_shell = df.fillna(value=df['root_shell'].mean())
df.root_shell.isnull().sum()

df['su_attempted'].mean()
df.su_attempted = df.fillna(value=df['su_attempted'].mean())
df.su_attempted.isnull().sum()

df['num_root'].mean()
df.num_root = df.fillna(value=df['num_root'].mean())
df.num_root.isnull().sum()

df['num_file_creations'].mean()
df.num_file_creations = df.fillna(value=df['num_file_creations'].mean())
df.num_file_creations.isnull().sum()

df['num_shells'].mean()
df.num_shells = df.fillna(value=df['num_shells'].mean())
df.num_shells.isnull().sum()

df['num_access_files'].mean()
df.num_access_files = df.fillna(value=df['num_access_files'].mean())
df.num_access_files.isnull().sum()

df['is_guest_login'].mean()
df.is_guest_login = df.fillna(value=df['is_guest_login'].mean())
df.is_guest_login.isnull().sum()

df['rerror_rate'].mean()
df.rerror_rate = df.fillna(value=df['rerror_rate'].mean())
df.rerror_rate.isnull().sum()

df['srv_rerror_rate'].mean()
df.srv_rerror_rate = df.fillna(value=df['srv_rerror_rate'].mean())
df.srv_rerror_rate.isnull().sum()

df['diff_srv_rate'].mean()
df.diff_srv_rate = df.fillna(value=df['diff_srv_rate'].mean())
df.diff_srv_rate.isnull().sum()

df['dst_host_count'].mean()
df.dst_host_count = df.fillna(value=df['dst_host_count'].mean())
df.dst_host_count.isnull().sum()

df['dst_host_srv_diff_host_rate'].mean()
df.dst_host_srv_diff_host_rate = df.fillna(value=df['dst_host_srv_diff_host_rate'].mean())
df.dst_host_srv_diff_host_rate.isnull().sum()
        
df['dst_host_rerror_rate'].mean()
df.dst_host_rerror_rate = df.fillna(value=df['dst_host_rerror_rate'].mean())
df.dst_host_rerror_rate.isnull().sum()
                 
df['dst_host_srv_rerror_rate'].mean()
df.dst_host_srv_rerror_rate  = df.fillna(value=df['dst_host_srv_rerror_rate'].mean())
df.dst_host_srv_rerror_rate.isnull().sum()                  
              
df['serror_rate'].mean()
df.serror_rate = df.fillna(value=df['serror_rate'].mean())
df.serror_rate.isnull().sum()               
       
#df['Target'].mode()
#df.Target = df.fillna(value=tar_mode)
#df.Target.isnull().sum()

df['srv_diff_host_rate'].mean()
df.srv_diff_host_rate = df.fillna(value=df['srv_diff_host_rate'].mean())
df.srv_diff_host_rate.isnull().sum()

0

In [9]:
#df.Target = df.fillna(value=tar_mode)
df.isnull().sum()
#df.Target.value_counts()

X                              0
duration                       0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
rerror_rate                    0
srv_rerror_rate                0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_diff_host_rate    0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
serror_rate                    0
Target                         0
dtype: int64

In [10]:
#x = df.drop(["Target","X"], axis=1)
x = df.drop(["Target"], axis=1)
x.columns
df.Target.head()
y = df.Target
y.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: Target, dtype: int64

In [11]:
x.isnull().sum()
y.isnull().sum()

0

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state = 99)

In [13]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier();

In [14]:
print(x.shape)
print(y.shape)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)
y.head()

(98000, 27)
(98000,)
(68600, 27) (29400, 27) (68600,) (29400,)


0    0
1    0
2    0
3    0
4    0
Name: Target, dtype: int64

In [15]:
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [16]:
lr = LogisticRegression(solver='lbfgs')
lr.fit(x_train,y_train)
result_lr = lr.predict(x_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score,auc,roc_curve
print(classification_report(y_test,result_lr))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     28960
           1       0.00      0.00      0.00       440

    accuracy                           0.99     29400
   macro avg       0.49      0.50      0.50     29400
weighted avg       0.97      0.99      0.98     29400



In [18]:
print(confusion_matrix(y_test,result_lr))

[[28960     0]
 [  440     0]]


In [19]:
fpr,tpr, threshold = roc_curve(y_test,result_lr)
roc_auc = auc(fpr,tpr)
print(roc_auc)

0.5


In [20]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree = dtree.fit(x_train,y_train)
resultdt = dtree.predict(x_test)

In [21]:
print(classification_report(y_test,resultdt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28960
           1       1.00      1.00      1.00       440

    accuracy                           1.00     29400
   macro avg       1.00      1.00      1.00     29400
weighted avg       1.00      1.00      1.00     29400



In [22]:
print(confusion_matrix(y_test,resultdt))

[[28960     0]
 [    0   440]]


In [23]:
fpr,tpr, threshold = roc_curve(y_test,resultdt)
roc_auc = auc(fpr,tpr)
print(roc_auc)

1.0


In [24]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
resultnb = gnb.predict(x_test)

In [25]:
print(classification_report(y_test,resultnb))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     28960
           1       0.51      1.00      0.67       440

    accuracy                           0.99     29400
   macro avg       0.75      0.99      0.83     29400
weighted avg       0.99      0.99      0.99     29400



In [26]:
print(confusion_matrix(y_test,resultnb))

[[28533   427]
 [    0   440]]


In [27]:
fpr,tpr, threshold = roc_curve(y_test,resultnb)
roc_auc = auc(fpr,tpr)
print(roc_auc)

0.9926277624309393


In [28]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [29]:
resultknn = classifier.predict(x_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, resultknn))
print(classification_report(y_test, resultknn))

[[28960     0]
 [    2   438]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28960
           1       1.00      1.00      1.00       440

    accuracy                           1.00     29400
   macro avg       1.00      1.00      1.00     29400
weighted avg       1.00      1.00      1.00     29400



In [31]:
fpr,tpr, threshold = roc_curve(y_test,resultknn)
roc_auc = auc(fpr,tpr)
print(roc_auc)

0.9977272727272728
